version: '3'
services:
  webserver:
    build:
      context: ./
    ports:
      - "8080:8080"
    depends_on:
      - "db"
    labels:
      kompose.service.type: LoadBalancer
  db:
    image: mysql:8
    ports:
      - "3306:3306"
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_DATABASE: blog
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
    volumes:
    - ./dump:/docker-entrypoint-initdb.d
    - /var/lib/mysql
    healthcheck:
      test: mysqladmin --user=$$MYSQL_USER --password=$$MYSQL_PASSWORD ping
      timeout: 5s
      retries: 5
      
  adminer:
    image: adminer
    restart: always
    ports:
      - 8088:8080  
