apiVersion: v1
kind: Service
metadata:
  name: webserver
  namespace: gowebservice
spec:
  ports:
    - name: "8080"
      port: 8080
      targetPort: 8080
  selector:
    app: webserver
status:
  loadBalancer: {}
