apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc
  namespace: mysqldatabase 
spec:
  storageClassName: standard 
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 25Gi