apiVersion: v1
kind: Service
metadata:
  namespace: mysqldatabase
  name: db
spec:
  ports:
    - name: "3306"
      port: 3306
      targetPort: 3306
  selector:
    app: db
status:
  loadBalancer: {}
